# Although this is a C++ project, we use different PHP versions
language: php

# we need bionic
dist: bionic
sudo: required
group: edge

php:
  - 7.3
  - 7.4


# setting the env is the easiest, because it will mix with all the separate php versions (travis does this)
env:
  - COMPILER_PKG=g++-7 COMPILER=g++-7
  - COMPILER_PKG=g++-8 COMPILER=g++-8
  - COMPILER_PKG=g++-9 COMPILER=g++-9

matrix:
  allow_failures:
    - php: nightly

before_install:
  # install access to all gcc compilers
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # update package index and install correct compiler
  - sudo apt-get -y update
  - sudo apt-get -y --allow-unauthenticated --no-install-recommends install ${COMPILER_PKG}

script:
  # simply make the project with the set compiler
  - make -j4 COMPILER=$COMPILER && sudo make install
